parameters:
  - name: Comment
    displayName: Comment - included in build number
    default: '-'
    type: string
  - name: Export
    displayName: Run an export operation before running the deployment - this is recommended to prevent any unintentional loss of changes made manually to the tenant
    default: true
    type: boolean
  - name: UseLastDeployTagForExport
    displayName: Gets the state of the last deployment, before doing an export - if unchecked, will use latest state of repo
    default: true
    type: boolean
  - name: Deploy
    displayName: Deploy changes to tenant - if unchecked, only performs a preview and will not make any changes to the tenant
    default: true
    type: boolean
  - name: ExportOnly
    displayName: Run as export only - if checked, will only run the Export operation without validation after export
    default: false
    type: boolean
variables:
  - group: Sync
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
schedules:
  - cron: 0 6 * * *
    displayName: Daily Run 6AM UTC
    branches:
      include:
        - master
    always: true
pool:
  vmImage: windows-latest
resources:
  repositories:
    - repository: Templates
      type: github
      name: simeoncloud/AzurePipelineTemplates
      ref: refs/heads/master
      endpoint: simeoncloud
    - repository: Sync
      type: github
      name: simeoncloud/Sync
      ref: refs/heads/master
      endpoint: simeoncloud
stages:
  - template: SimeonSync.yml@Templates
    parameters:
      Comment: ${{ parameters.Comment }}
      Export: ${{ parameters.Export }}
      ExportOnly: ${{ parameters.ExportOnly }}
      UseLastDeployTagForExport: ${{ parameters.UseLastDeployTagForExport }}
      UpdateBaseline: false
      Deploy: ${{ parameters.Deploy }}